#tomcat conf
server:
  port: 8082

  #  配置redis
spring:
  redis:
    host: 192.168.192.128
    port: 6397
    password:
    timeout: 1000
    database: 0

    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

    #     配置solr
  data:
    solr:
      host: http://192.168.192.128:8080/solr/collection1

